// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[WHITESPACE-2]
	_ = x[INDENT-3]
	_ = x[NEWLINE-4]
	_ = x[INT-5]
	_ = x[DECIMAL-6]
	_ = x[STRING-7]
	_ = x[TEXT-8]
	_ = x[BANG-9]
	_ = x[STAR-10]
	_ = x[PERCENT-11]
	_ = x[HASH-12]
	_ = x[SEMICOLON-13]
	_ = x[COLON-14]
	_ = x[EQ-15]
	_ = x[EQEQ-16]
	_ = x[EQEQEQ-17]
	_ = x[EQSTAR-18]
	_ = x[AT-19]
	_ = x[ATAT-20]
	_ = x[PIPE-21]
	_ = x[PLUS-22]
	_ = x[MINUS-23]
	_ = x[TILDE-24]
	_ = x[LPAREN-25]
	_ = x[RPAREN-26]
	_ = x[LBRACE-27]
	_ = x[LBRACELBRACE-28]
	_ = x[RBRACERBRACE-29]
	_ = x[RBRACE-30]
	_ = x[LBRACKET-31]
	_ = x[RBRACKET-32]
	_ = x[COMMODITYMARK-33]
	_ = x[DATE-34]
	_ = x[TIME-35]
	_ = x[PARENEXPR-36]
	_ = x[COMMENTKW-37]
	_ = x[ACCOUNT-38]
	_ = x[COMMODITY-39]
	_ = x[INCLUDE-40]
	_ = x[ALIAS-41]
	_ = x[PAYEE-42]
	_ = x[TAG-43]
	_ = x[APPLY-44]
	_ = x[END-45]
	_ = x[YEAR-46]
	_ = x[DECIMALMARK-47]
	_ = x[D-48]
	_ = x[P-49]
	_ = x[N-50]
	_ = x[C-51]
}

const _Type_name = "ILLEGALEOFWHITESPACEINDENTNEWLINEINTDECIMALSTRINGTEXTBANGSTARPERCENTHASHSEMICOLONCOLONEQEQEQEQEQEQEQSTARATATATPIPEPLUSMINUSTILDELPARENRPARENLBRACELBRACELBRACERBRACERBRACERBRACELBRACKETRBRACKETCOMMODITYMARKDATETIMEPARENEXPRCOMMENTKWACCOUNTCOMMODITYINCLUDEALIASPAYEETAGAPPLYENDYEARDECIMALMARKDPNC"

var _Type_index = [...]uint16{0, 7, 10, 20, 26, 33, 36, 43, 49, 53, 57, 61, 68, 72, 81, 86, 88, 92, 98, 104, 106, 110, 114, 118, 123, 128, 134, 140, 146, 158, 170, 176, 184, 192, 205, 209, 213, 222, 231, 238, 247, 254, 259, 264, 267, 272, 275, 279, 290, 291, 292, 293, 294}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
