// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[WHITESPACE-2]
	_ = x[INDENT-3]
	_ = x[NEWLINE-4]
	_ = x[INT-5]
	_ = x[DECIMAL-6]
	_ = x[STRING-7]
	_ = x[TEXT-8]
	_ = x[BANG-9]
	_ = x[STAR-10]
	_ = x[PERCENT-11]
	_ = x[HASH-12]
	_ = x[SEMICOLON-13]
	_ = x[COLON-14]
	_ = x[EQ-15]
	_ = x[EQEQ-16]
	_ = x[EQEQEQ-17]
	_ = x[AT-18]
	_ = x[ATAT-19]
	_ = x[PIPE-20]
	_ = x[PLUS-21]
	_ = x[MINUS-22]
	_ = x[TILDE-23]
	_ = x[LPAREN-24]
	_ = x[RPAREN-25]
	_ = x[LBRACE-26]
	_ = x[LBRACELBRACE-27]
	_ = x[RBRACERBRACE-28]
	_ = x[RBRACE-29]
	_ = x[LBRACKET-30]
	_ = x[RBRACKET-31]
	_ = x[COMMODITYMARK-32]
	_ = x[DATE-33]
	_ = x[TIME-34]
	_ = x[PARENEXPR-35]
	_ = x[COMMENTKW-36]
	_ = x[ACCOUNT-37]
	_ = x[COMMODITY-38]
	_ = x[INCLUDE-39]
	_ = x[ALIAS-40]
	_ = x[PAYEE-41]
	_ = x[TAG-42]
	_ = x[APPLY-43]
	_ = x[END-44]
	_ = x[YEAR-45]
	_ = x[DECIMALMARK-46]
	_ = x[D-47]
	_ = x[P-48]
	_ = x[N-49]
}

const _Type_name = "ILLEGALEOFWHITESPACEINDENTNEWLINEINTDECIMALSTRINGTEXTBANGSTARPERCENTHASHSEMICOLONCOLONEQEQEQEQEQEQATATATPIPEPLUSMINUSTILDELPARENRPARENLBRACELBRACELBRACERBRACERBRACERBRACELBRACKETRBRACKETCOMMODITYMARKDATETIMEPARENEXPRCOMMENTKWACCOUNTCOMMODITYINCLUDEALIASPAYEETAGAPPLYENDYEARDECIMALMARKDPN"

var _Type_index = [...]uint16{0, 7, 10, 20, 26, 33, 36, 43, 49, 53, 57, 61, 68, 72, 81, 86, 88, 92, 98, 100, 104, 108, 112, 117, 122, 128, 134, 140, 152, 164, 170, 178, 186, 199, 203, 207, 216, 225, 232, 241, 248, 253, 258, 261, 266, 269, 273, 284, 285, 286, 287}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
